services:

  db:
    image: mysql:8.0
    container_name: projets-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projets_db
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 12

  backend:
    build: ./backend
    container_name: projets-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/projets_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: devops
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: projets-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
